### ISSUE TITLE
calcofi website down thus breaking link-check

### ISSUE THREAD

**Issue by MathewBiddle** [NOAA-PSL/CEFI-info-hub-list#111]
See https://github.com/NOAA-PSL/CEFI-info-hub-list/actions/runs/7128326823/job/19410073177#step:4:1

Maybe the process should be more lenient in checking links? Or less frequently checking?

**Comment by chiaweh2** [comment]
Agreed. I actually update the original pytest to the one that can check both the html response and the actual accessibility of the website since some seems to have 404 with accessible website. 

The problem of less frequent check is if the check happened when a certain site is down, the check test would appear fail till the next test. So I think a more frequent test would actually show a more real time result and catch the fix of the website better. But you are certainly right, I might need to tweak on the code to be more leninent.

**Comment by chiaweh2** [comment]
After about a month of testing the new strategy (high frequency check), the link check seems to work okay (showing PASS once the website is fixed with around 4 checks per day). So I will close this issue for now. Feel free to reopen if there is problem surfacing or not fixed.
