### ISSUE TITLE
Consider moving to NOAA repo organization?

### ISSUE THREAD

**Issue by MathewBiddle** [NOAA-PSL/CEFI-info-hub-list#27]
I'm wondering if we should consider moving this to a NOAA github organization? 

Maybe under https://github.com/NOAA-PSL? 

I could discuss with IOOS to move to https://github.com/ioos (I have admin priv's there).

**Comment by chiaweh2** [comment]
Yes, I agree! I was planning to move the repo to NOAA-PSL. But Mike also bring up ideas about creating a CEFI specific account. Do you think this is something worth doing? Currently, we have the list and the cookbook that I think can be hosted  under the account if we decided to make one.

**Comment by MathewBiddle** [comment]
YES! Make a `NOAA-CEFI` organization which can contain these various repositories. At least that's my thought. 

https://github.com/noaa-cefi ?

**Comment by chiaweh2** [comment]
Okay. I will bring this up later today with Mike!

**Comment by eugeneburger** [comment]
Good point Matt - That also allow the 2FA enforcement.

Do we expect many non-NOAA collaborators on this. I'm happy to help with the migration.

**Comment by chiaweh2** [comment]
Thanks @eugeneburger for the suggestions! I have a quick question. How restrictive on the GitHub action it is in the NOAA account. I was surprised that an enterprise account can do less than a personal account.

**Comment by chiaweh2** [comment]
@MathewBiddle @eugeneburger As a test, I have moved the cefi-cookbook  repo to NOAA-PSL https://github.com/NOAA-PSL/cefi-cookbook . Couple things that I discovered after the test.

- The GitHub page works right away with new link https://noaa-psl.github.io/cefi-cookbook/content/intro.html  (the old link will not redirect so it is good that we start moving now instead of later)
- I will need admin role in the repo to better manage how the repo is handling merge, GitHub action, and some other related setting (this needs NOAA-PSL admin helps ). 
- All commit history is preserved. Based on https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository# , the PR issue and collaborator should also be preserved.
- I can also transfer again from NOAA-PSL to other organization if needed.

So if it is okay with you, I will transfer this repo to NOAA-PSL as a temporary solution instead of keep It under my personal account. In the meantime, we can discuss on if a NOAA-CEFI organization account is needed.

**Comment by eugeneburger** [comment]
@chiaweh2 That is good and thank you for the update. This gets us closer to what NOAA expects with repos. I suggest requiring 2FA on repos in the organizational account.

Since we're not paying for this account, I suppose we do not have to use the Enterprise license.

Submit a pull request to add this organizational account to the readme file [in this repo](https://github.com/NOAAGov/NOAA-Affiliated-Projects), and I will accept that.

**Comment by MathewBiddle** [comment]
This is fantastic! Thank you @chiaweh2!

Would it be beneficial to have me as an administrator on the repo as well? I don't foresee myself need the privilege's, but it might be good to have multiple folks with the ability to make changes when needed.

**Comment by chiaweh2** [comment]
I just made @MathewBiddle the admin too for the repo! I will close the issue for now. But feel free to open it when a discussion on creating the CEFI GitHub is needed
